In [4]:
import torch
import torch.nn.functional as F

In [2]:
input = torch.tensor([[1, 2, 0, 3, 1],
                      [0, 1, 2, 3, 1],
                      [1, 2, 1, 0, 0],
                      [5, 2, 3, 1, 1],
                      [2, 1, 0, 1, 1]])

kernel = torch.tensor([[1, 2, 1],
                       [0, 1, 0],
                       [2, 1, 0]])

print(input.shape)
print(kernel.shape)

torch.Size([5, 5])
torch.Size([3, 3])


In [3]:
input = torch.reshape(input, (1, 1, 5, 5))
kernel = torch.reshape(kernel, (1, 1, 3, 3))
print(input.shape)
print(kernel.shape)

torch.Size([1, 1, 5, 5])
torch.Size([1, 1, 3, 3])


In [5]:
output = F.conv2d(input, kernel, stride=1)
print(output)

tensor([[[[10, 12, 12],
          [18, 16, 16],
          [13,  9,  3]]]])


In [6]:
output2 = F.conv2d(input, kernel, stride=2)
print(output2)

tensor([[[[10, 12],
          [13,  3]]]])


In [7]:
output3 = F.conv2d(input, kernel, stride=1, padding=1)
print(output3)

tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])
